# Generated by Django 2.0.5 on 2018-08-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDistribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, '正在跟进'), (2, '已报名'), (3, '三天未跟进'), (4, '15天未成单')], default=1)),
                ('memo', models.CharField(max_length=255)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycrm.UserInfo', verbose_name='课程顾问')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='mycrm.Customer')),
            ],
        ),
    ]
